Fix #164
robotology/wearables pull request #168
Opened 2022-09-22 07:52 UTC by lrapetti

As suggested by @traversaro in https://github.com/robotology/wearables/issues/164#issuecomment-1247799135 `find_package(IWear)` should not be called in the `IWearFrameVisualizer`

2022-09-22 08:06 UTC, RiccardoGrieco approved these changes

2022-09-22 08:20 UTC, traversaro commented
Are you sure this is working? For some reason, the `IWear` target is referenced in the build directory as `Wearable::IWear` (see https://github.com/robotology/wearables/blob/0ba0bfc5c3e84afd1ebaa14811aad5d55e8a70a9/interfaces/IWear/CMakeLists.txt#L29), while when it is installed is `IWear::IWear` (see https://github.com/robotology/wearables/blob/0ba0bfc5c3e84afd1ebaa14811aad5d55e8a70a9/interfaces/IWear/CMakeLists.txt#L63 and https://github.com/robotology/wearables/blob/0ba0bfc5c3e84afd1ebaa14811aad5d55e8a70a9/modules/IWearFrameVisualizer/CMakeLists.txt#L29).

Furthermore, I think you are still not compiling this in CI until we move https://github.com/robotology/wearables/blob/0ba0bfc5c3e84afd1ebaa14811aad5d55e8a70a9/CMakeLists.txt#L97 before `add_subdirectory(modules)` . 

My suggestions:
* Change the alias in https://github.com/robotology/wearables/blob/0ba0bfc5c3e84afd1ebaa14811aad5d55e8a70a9/interfaces/IWear/CMakeLists.txt#L29 from `Wearable::IWear` to `IWear::IWear`
* Move https://github.com/robotology/wearables/blob/0ba0bfc5c3e84afd1ebaa14811aad5d55e8a70a9/CMakeLists.txt#L97 before any `add_subdirectory` call

2022-09-22 08:21 UTC, traversaro requested changes
See comments, I would not merge this as it also breakes the only (super-strange) way in which the visualizer is working. @lrapetti if you want I can quickly explain this face2face, as I imagine it is not straightforward to understand how this works even with my comments.

2022-09-23 13:45 UTC, lrapetti commented
> See comments, I would not merge this as it also breakes the only (super-strange) way in which the visualizer is working. @lrapetti if you want I can quickly explain this face2face, as I imagine it is not straightforward to understand how this works even with my comments.

Also @RiccardoGrieco had some concerns about the current cmake structure, we can have a f2f alignment next week.

2023-02-06 17:27 UTC, RiccardoGrieco commented
@traversaro I guess we can close this since we merged #182, right?

2023-02-06 20:18 UTC, traversaro commented
> @traversaro I guess we can close this since we merged #182, right?

Ok!

2023-02-07 13:18 UTC, lrapetti commented
The original problem was solved by @traversaro with https://github.com/robotology/wearables/pull/182. Thanks a lot!

2023-02-07 13:18 UTC, closed without merging